### ISSUE TITLE
POST请求异常死循环问题

### ISSUE THREAD

**Issue by haozi2015** [scxwhite/hera#108]
http外部调用，执行任务时，勿将GET请求写成POST方式，造成系统死循环。
原因：
异常拦截器返回error.index页面，被登录拦截器拦截，重定向至/login请求，但请求方式还是POST，造成POST方式的/login请求不存在，再次进入异常拦截器，不断重复。

**Comment by scxwhite** [comment]
对提供给外部的http请求方法上或者类上要加：@UnCheckLogin注解，该注解不会进行登录判断

**Comment by haozi2015** [comment]
> 对提供给外部的http请求方法上或者类上要加：@UnCheckLogin注解，该注解不会进行登录判断



> 对提供给外部的http请求方法上或者类上要加：@UnCheckLogin注解，该注解不会进行登录判断

那个接口只是触发的点，其它不存在的URL，只要是POST方式，就会触发死循环。

**Comment by scxwhite** [comment]
感谢 我修复下
