### ISSUE TITLE
sudo: source: command not found

### ISSUE THREAD

**Issue by gj-zhang** [scxwhite/hera#28]
执行echoTest 的例子， 报错。 
![image](https://user-images.githubusercontent.com/21170229/58331726-53dbeb00-7e6c-11e9-8487-45560d9a29d2.png)
看了一下生成出来的run.sh 脚本， 也看了下代码。问下为啥这边要加一个source命令？

**Comment by scxwhite** [comment]
这个使用sh 也是可以的，没有特殊要求

**Comment by jiangeyu** [comment]
AbstractJob 这个类加个参数 -s  可以搞定  sudo -s -E -u

**Comment by gj-zhang** [comment]
好的 谢谢
