### ISSUE TITLE
release2.3.1新建任务手动执行无法选择版本

### ISSUE THREAD

**Issue by vickyi** [scxwhite/hera#37]
![image](https://user-images.githubusercontent.com/1571275/63084167-2be8b900-bf7d-11e9-9af9-b46d8c5d82b6.png)

version：release2.3.1
新建任务后，生成版本成功，但是接下来手动执行时，选择版本的时候，下拉框不可用，无法选择版本，提交后也没有任务执行。

测试浏览器：Chrome、Firefox、Safari

**Comment by scxwhite** [comment]
目前只对新建任务的定时任务生成版本，如果是依赖任务，需要等待每个小时的整点生成。或者自己触发一次全量版本生成
