### ISSUE TITLE
hera_action的description和hera_job的description字段长度不一致导致生产事故

### ISSUE THREAD

**Issue by lixiaozhan1** [scxwhite/hera#44]
CREATE TABLE `hera_action`
  `description`          varchar(256)   DEFAULT NULL COMMENT '版本描述',
CREATE TABLE `hera_job`
  `description`          varchar(2000) DEFAULT NULL COMMENT '任务描述',

hera_job的description输入长度超过256时，任务能保存成功，第二天凌晨批量生成版本时，因为某条版本插入失败影响到其他正常任务的版本生成，导致生产事故。

**Comment by scxwhite** [comment]
感谢。后面版本我会修复这个bug

**Comment by scxwhite** [comment]
目前使用的版本你们可以通过生成版本时catch异常和修改hera_job表与hera_action 长度一直来规避
