### ISSUE TITLE
bin/start.sh不能在任何位置执行

### ISSUE THREAD

**Issue by jet2007** [scxwhite/hera#48]
bin目录
start.sh/restart 不能在任何位置执行; 
stop.sh的命令：[ps aux | grep java | grep hera | awk '{print $2}] 不太严格,增加更多条件，避免 [ps aux | grep java | grep hera | grep jar |grep server | awk '{print $2}]

参考code 
curDir=$(cd `dirname $0`; pwd)
scriptName=`basename $0`
cd ${curDir}

**Comment by scxwhite** [comment]
感谢，已经修复
