### ISSUE TITLE
WorkHandler中的问题

### ISSUE THREAD

**Issue by fanglongshuang** [scxwhite/hera#68]
com.dfire.core.netty.worker.WorkHandler中removeListener方法和addListener方法一样，这个removeListener方法是写错了还是特意这样写的：
public void removeListener(ResponseListener listener) {
        listeners.add(listener);
}

**Comment by scxwhite** [comment]
我看是写错了。你可以提交个pr修复一下吗？

**Comment by scxwhite** [comment]
https://github.com/scxwhite/hera/pull/69
