### ISSUE TITLE
关于调度任务的一些建议

### ISSUE THREAD

**Issue by wing1995** [scxwhite/hera#81]
1、任务日志显示运行成功，且exitCode=0，但是任务状态仍然是running，导致后面的任务只能wait，目前的方案只能去任务详情一个个把任务强制改为成功，后面的任务才会继续运行；
2、强烈建议在任务详情页面增加批量下发任务，即遇到多个任务下发失败，我可以输入这些任务列表，比如换行或都好分割，通过批量下发或者批量恢复来运行任务，而不是一个个恢复；以此类任务重跑页面也能够实现批量任务重跑，比如上游的任务重跑了最近1年的数据，下游的任务也批量重跑最近一年的数据

**Comment by scxwhite** [comment]
1.一般是由于网络抖动导致的任务状态无法写入成功，这个需要开发一个检测的功能来判断任务是否已经完成。当然，也有意在后面版本增加设置任务状态的按钮。
2.批量下发任务可以实现，但是如果说恢复一个，就恢复下游所有任务，这个功能实现有些繁琐，不过也在实现中了。

**Comment by wing1995** [comment]
> 1.一般是由于网络抖动导致的任务状态无法写入成功，这个需要开发一个检测的功能来判断任务是否已经完成。当然，也有意在后面版本增加设置任务状态的按钮。
> 2.批量下发任务可以实现，但是如果说恢复一个，就恢复下游所有任务，这个功能实现有些繁琐，不过也在实现中了。
Thanks!
